test for variants getting built correctly

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -77,3 +77,26 @@ jobs:
             exit 1
           fi
           ls -al conda_package_customized_build
+
+  # Test variants
+  customized-yml:
+    runs-on: ubuntu-latest
+    steps:
+      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+      - uses: actions/checkout@v2
+      # Runs this action, skipping the build but running successfully
+      - uses: ./
+        with:
+          CONDA_BUILD_ENV_FILEPATH: 'test_env/test_build.yml'
+          TEST_RESULTS_ARTIFACT_NAME: 'customized_test_results'
+          PACKAGE_ARTIFACT_NAME: 'conda_package_customized_build'
+          BUILD_OPTIONS: "--variants '{python: [3.7, 3.8]}'"
+      - uses: actions/download-artifact@v2
+      - name: Check Artifacts
+        run: |
+          ls -al
+          if [ ! -e conda_package_customized_build ]; then
+            echo "conda_package artifact not found"
+            exit 1
+          fi
+          ls -al conda_package_customized_build
